#!/usr/bin/env bash
# CRUD de metadatos
: '
  Herramienta para crear un registro de cambios en sistema de archivos personales del usuario.
  Luego puede crear, leer, actualizar y borrar los metadatos que no necesite.
'
cat << INICIO
  Crear, leer, actualizar y borrar metadatos en archivos.
INICIO
red_="\e[1;31m" ;green_="\e[0;32m" ;blue_="\e[0;34m" ;yellow_="\e[0;33m" ;purple_="\e[0;35m" ;turquesa_="\e[0;36m" ;gray_="\e[0;37m" ;end_="\e[m" ;

ERROR(){
cat << EOF
  please install exiftool
EOF
}
# Leer metadatos de todos los archivos de directorio principal de usuario.
(cd ; cat .metadata-crud >> .incremental-metadatacrud ; find . > .metadata-crud ; cat .metadata-crud | xargs exiftool >> ~/metadatos_en_archivos_de_usuario)

echo "   Se han registrado todos los metadatos de directorio de usuario."
# Create, read, update and delete
MetadataCrud()
{
  CRUD()
  {
    # actualizar metadatos
    find . | xargs exiftool -all="$1"
  }
  (cd ;CRUD ' ')
}
read -p "Esta seguro que desea actualizar los metadatos? \n\t[ENTER] continuar\t[Ctrl+C] salir" CONFIRMAR
MetadataCrud 2>& /dev/null || ERROR