#!/usr/bin/env bash
#
chars="dbpqdbpq"
bars='|/-\|-'
while :; do
	# 	echo -e "[\e[1;33;40m${symbol}\e[m]\r"
	for ((i = 0; i < ${#chars}; i++)); do
		sleep 0.03
		echo -en "    [\e[1;3$i;40m${chars:$i:1}\e[m] cargando" "\r"
	done

done
