#!/usr/bin/env bash
# leer bandeja de entrada de correo electronico por terminal
function dumpemail()
{
curl -u $USERNAME:$PASSWORD --silent "https://mail.google.com/mail/feed/atom" | tr -d '\n' | awk -F '<entry>' '{for (i=2; i<=NF; i++) {print $i}}' | sed -n "s/<title>\(.*\)<\/title.*name>\(.*\)<\/name>.*/\2 - \1/p"
}

read -p "Username: " USERNAME
read -p "Password: " PASSWORD


dumpemail || echo 'datos incorrectos'