#!/bin/bash
# Desactiva temporalmente el aslr, para sesiones de "kernel exploiting"

function ojosfuriosos()
{
echo '   :.:.:.:. ----= Memory protection OFF =---- .:.:.:.:'
echo -e "\n\nASLR disabled for this session \n"
setarch "$(uname -m)" -R bash --rcfile <(echo "PS1='no-aslr $ '") -i
echo "==== ASLR re-enabled ===="
}


(ojosfuriosos)