#!/usr/bin/env bash
: '
	creacion de servicio (daemon)
'

function alerta() {
	function ayuda() {
		cat <<DESCRIPCION_AYUDA
SYNOPIS
$0 [SEGUNDOS]
DESCRIPCION
Escribe la fecha cada X segundos en el log '~/alerta.log'
CODIGOS DE RETORNO
0 Si no hay ningún error
DESCRIPCION_AYUDA
	}
	# si primer parámetro == 'h' o == 'help'
	if [ "$1" == "h" ]; then
		ayuda
		exit 0
	fi

	function main() {
		DEFAULT=2
		# comprobar que SEGUNDOS es un número
		if [ "$SEGUNDOS" != "0" -a "$(echo $SEGUNDOS | awk '{ print $1 * 1 }')" != "$SEGUNDOS" ]; then
			echo "El parámetro '$1' no es un número. Se cogerá el valor por defecto ($DEFAULT)"
			SEGUNDOS=$DEFAULT
		fi
		# reinicio alerta.log
		echo "" >~/alerta.log
		while :; do
			date +%d/%m/%Y" "%H:%M:%S >>~/alerta.log
			sleep $SEGUNDOS
		done
	}
	echo $$
	main $1
}

function servicio() {
	# función de ayuda
	function ayuda() {
		cat <<DESCRIPCION_AYUDA
SYNOPIS
$0 start|stop|restart|status
DESCRIPCIÓN
Muestra que arraca, para, relanza y nos muestra el estado de 'alerta'.
CÓDIGOS DE RETORNO
0 Si no hay ningún error.
DESCRIPCION_AYUDA
	}
	DAEMON='alerta'
	PIDFILE=/tmp/$DAEMON.pid
	# función que arranca 'alerta'
	function do_start() {
		# si exite el fichero
		if [ -e $PIDFILE ]; then
			echo "El proceso ya se está ejecutando."
			exit 0
		fi
		$DAEMON 5 &
		echo $! >$PIDFILE
		echo "Ejecutandose..."
	}
	# función que para 'alerta'
	function do_stop() {
		# si exite el fichero
		if [ -e $PIDFILE ]; then
			kill 9 $(echo $PIDFILE)
			rm $PIDFILE
		fi
		echo "Parado."
	}
	# función que para y arrance 'alerta'
	function do_restart() {
		do_stop
		do_start
	}
	# función que muestra el estado de 'alerta'
	function do_status() {
		# si exite el fichero
		if [ -e $PIDFILE ]; then
			echo "Ejecutandose..."
		else
			echo "Parado."
		fi
	}
	# si primer parámetro == 'h' o == 'help'
	if [ "$1" == "h" -o "$1" == "help" ]; then
		ayuda
		exit 0
	fi

	case "$1" in
	start)
		do_start
		;;
	stop)
		do_stop
		;;
	restart)
		do_restart
		;;
	status)
		do_status
		;;
	*)
		echo "Parámetro '$1' incorrecto."
		;;
	esac
}

servicio "$1"
